name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1
    # - name: PHPUnit tests
    #   uses: php-actions/phpunit@v1
    #   with:
    #     config: phpunit.xml
    #     memory: 256M

    # - name: Validate composer.json and composer.lock
    #   run: composer validate

    # - name: Install dependencies
    #   run: composer install 

    - name: Run tests
      run: ./vendor/bin/phpunit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
