name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v1
    # - name: PHPUnit tests
    #   uses: php-actions/phpunit@v1
    #   with:
    #     config: phpunit.xml
    #     memory: 256M

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: send codecov
      run: bash <(curl -s https://codecov.io/bash) -t token
